# DISCRIMINANT ANALYSIS

In this coding assignment you are to implement a Minimum Risk Bayes Decision Theoretic classifier and use it to classify the test examples in the provided datasets.  
Assume the following:
1. All conditional density functions are multivariate Gaussian
2. Each class has its own covariance matrix
3. Equally likely prior probabilities
4. 0-1 loss function


## Training Phase

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.linalg import logm, expm

# Load training data - 135 observations, 4 features, 3 classes, 
df = pd.read_csv("iris_corrupted_training_data.csv")
print(df.head())
df = df.values
tr_data = df

# Load validation data - 15 samples
df = pd.read_csv("iris_validation_data.csv")
print(df.head())
df = df.values
val_data = df



   sepal_length   sepal_width   petal_length   petal_width   class
0        5.7147        2.6743         3.2696       1.65440       2
1        5.1734        3.7374         5.9442       3.00050       3
2        7.3776        3.1505         3.3543       0.64839       2
3        6.4908        2.3983         3.3917       1.54950       2
4        6.8182        3.4016         4.7495       0.57970       3
   sepal_length   sepal_width   petal_length   petal_width   class
0           4.4           2.9            1.4           0.2       1
1           6.7           3.0            5.2           2.3       3
2           4.9           3.1            1.5           0.2       1
3           5.1           2.5            3.0           1.1       2
4           6.1           3.0            4.6           1.4       2


In [2]:
# Covariance MLE function
def covmle(data, mean):
    """
      data is a matrix size N x 4
      mean is a vector size 4 x 1
    """
    X = np.array(data[:,0:4])
    m = np.array(mean)
    XM = X - m
    #print(np.shape(mean))
    return np.dot(XM.transpose(), XM) / len(X)

In [4]:
# TO DO: Compute various components of the disriminant function
# 
# Suggestion: create data matrices for each class
# ...

#create data matrices for each of the 3 classes
class1_arr = []
class2_arr = []
class3_arr = []


for i in range(0, len(tr_data)):
    if tr_data[i][4] == 1:
        class1_arr.append([])
        #add in data 0-3 in row i to class1_arr
        for j in range(0, 4):
            class1_arr[len(class1_arr)-1].append(tr_data[i][j])
            
    if tr_data[i][4] == 2:
        class2_arr.append([])
        #add in data 0-3 in row i to class1_arr
        for j in range(0, 4):
            class2_arr[len(class2_arr)-1].append(tr_data[i][j])
            
    if tr_data[i][4] == 3:
        class3_arr.append([])
        #add in data 0-3 in row i to class1_arr
        for j in range(0, 4):
            class3_arr[len(class3_arr)-1].append(tr_data[i][j])
            

# Would normally have to make each length different for each class, but each has 45/label
L = len(class1_arr)
    

# Find the mean_and the covariance_for each class
# Use the above covariance function


#sum the totals of the columns for each of the 3 arrays to later find the mean
arr1_means = [sum(x) for x in zip(*class1_arr)]
arr2_means = [sum(x) for x in zip(*class2_arr)]
arr3_means = [sum(x) for x in zip(*class3_arr)]

#take the total sum of each of the columns and then divide each element by L=45 to get the mean
arr1_means = [x / L for x in arr1_means]
arr2_means = [x / L for x in arr2_means]
arr3_means = [x / L for x in arr3_means]


#compute the covarience array using each class array and means
arr1_cov = covmle(np.asarray(class1_arr), arr1_means)
arr2_cov = covmle(np.asarray(class2_arr), arr2_means)
arr3_cov = covmle(np.asarray(class3_arr), arr3_means)




# Compute the determinant, the log and the inverse log
# ...


#compute the determinant of each covarience matrix
arr1_d = np.linalg.det(arr1_cov)
arr2_d = np.linalg.det(arr2_cov)
arr3_d = np.linalg.det(arr3_cov)


#compute the log of each class determinant
arr1_detlog = np.log(np.linalg.det(arr1_cov))
arr2_detlog = np.log(np.linalg.det(arr2_cov))
arr3_detlog = np.log(np.linalg.det(arr3_cov))

#compute the inv of the cov matrix using numpy function
arr1_covinv = np.linalg.inv(arr1_cov)
arr2_covinv = np.linalg.inv(arr2_cov)
arr3_covinv = np.linalg.inv(arr3_cov)




In [5]:
# TO DO: Print the mean vectors and the covariance matrices

print("means for class 1, 2, 3:")
print()
print(arr1_means)
print()
print(arr2_means)
print()
print(arr3_means)
print()


print()
print("Covariance matrix for class 1, 2, 3:")
print(arr1_cov)
print()
print(arr2_cov)
print()
print(arr3_cov)
print()


means for class 1, 2, 3:

[4.800817777777779, 3.487995555555555, 1.2692098888888892, 0.3478773333333334]

[6.065882222222223, 2.822879777777778, 4.262413333333334, 1.1078519666666666]

[6.42966, 2.956569555555556, 5.558746666666666, 1.9247654666666674]


Covariance matrix for class 1, 2, 3:
[[ 0.72206319 -0.09570774  0.15849484  0.09220771]
 [-0.09570774  1.02194573  0.08067128  0.05986411]
 [ 0.15849484  0.08067128  0.73711485  0.07575562]
 [ 0.09220771  0.05986411  0.07575562  0.502064  ]]

[[ 1.00385223  0.15694398  0.28097557 -0.10609686]
 [ 0.15694398  0.78627333  0.19772005 -0.07156185]
 [ 0.28097557  0.19772005  0.72402688 -0.04282879]
 [-0.10609686 -0.07156185 -0.04282879  0.68125752]]

[[1.33244449 0.26017373 0.43578404 0.29662547]
 [0.26017373 1.01624949 0.12567658 0.18028235]
 [0.43578404 0.12567658 0.68059088 0.22510266]
 [0.29662547 0.18028235 0.22510266 0.83851244]]



## Validation phase

In [84]:
# Evaluate model accuracy with validation data

# For each sample, compute the discriminant function (g1, g2, g3) corresponding to each class
# Assume prior = 1/3
# The predicted class label is the largest of g1, g2, g3
# Count the number of correctly predicted labels

correct_class = 0;  # number of correctly predicted label


#################
#variable names (for class 1. replace 1 with 2/3 for other classes):
#
#class1_arr = original data in for each class                 size: 45x4
#arr1_means = mean vector                                     size: 4x1
#arr1_d = determinant of cov matrix                           size: scalar value
#arr1_cov = covarience matrix                                 size: 4x4
#arr1_detlog = log of the covarience matrix                   size: scalar value
#arr1_covinv = inverseof the covarience matrix                size: 4x4
#
#################

d = 4

for i in range(0, len(val_data)):
    #CLASS 1:
    xmean = arr1_means - val_data_nc[i]
    #compute the ((-.5) * mean^t * cov * mean) term separately for clarity
    meancov = ((-.5) * np.matmul(np.matmul(np.transpose(xmean), arr1_cov), xmean))
    g1 = meancov - ((d/2)* np.log(2*np.pi)) - ((.5)*arr1_detlog) + np.log(1/3)
    
    #CLASS2:
    xmean = arr2_means-val_data_nc[i]
    #compute the ((-.5) * mean^t * cov * mean) term separately for clarity
    meancov = ((-.5) * np.matmul(np.matmul(np.transpose(xmean), arr2_cov), xmean))
    g2 = meancov - ((d/2)* np.log(2*np.pi)) - ((.5)*arr2_detlog) + np.log(1/3)
    
    #CLASS3:
    xmean = arr3_means-val_data_nc[i]
    #compute the ((-.5) * mean^t * cov * mean) term separately for clarity
    meancov = ((-.5) * np.matmul(np.matmul(np.transpose(xmean), arr3_cov), xmean))
    g3 = meancov - ((d/2)* np.log(2*np.pi)) - ((.5)*arr3_detlog) + np.log(1/3)
    
    
    gi = max(g1,g2,g3)
    if (gi == g1):
        gi = 1
    elif (gi == g2):
        gi = 2
    elif (gi == g3):
        gi = 3
    if (gi == val_data[i][4]):
        correct_class += 1
    
    
print('Classification accuracy = ', '{0:.4f}'. format(correct_class/15))



Classification accuracy =  0.8667
